### ISSUE TITLE
AboutからいけるHistoryページが404

### ISSUE THREAD

**Issue by KO1231** [TechUni2020/TechUni-hp#55]
Aboutページからいける各年度の年表(History)ページが404を返すようになっている。
![image](https://github.com/TechUni2020/TechUni-hp/assets/124903312/b7c92599-8692-4e65-8deb-072f7a4a4ccd)
![image](https://github.com/TechUni2020/TechUni-hp/assets/124903312/7f5bd272-fc00-4a59-8e0f-6c528cd33db2)

**Comment by KO1231** [comment]
Buttonタグのhrefで遷移しているけど、この実装でちゃんとルーティングしてくれているのかが不明
-> もしかしたらここでルーティングされていないから404されてる説

https://github.com/TechUni2020/TechUni-hp/blob/d622e2cf18e3d6fa3710d8432dac34369f0a5925/src/components/About/About.jsx#L87C1-L92C18

**Comment by KO1231** [comment]
.htaccessの追加で修正
-> @gohan5858 確認おねしゃす

**Comment by gohan5858** [comment]
OKです！
