### ISSUE TITLE
ルート以外のページに直接行くと404を吐く

### ISSUE THREAD

**Issue by KO1231** [TechUni2020/TechUni-hp#57]
[ルート](https://techuni.org/)に行って経由でabout等に行く分には問題ないが、直接[about](http://techuni.org/about)などルート以外のページに行こうとすると404がでる。

**Comment by KO1231** [comment]
.htaccessの追加で修正
-> @gohan5858 確認おねしゃす

**Comment by gohan5858** [comment]
OKです！
