### ISSUE TITLE
READMEの仕様技術と実装とが乖離している

### ISSUE THREAD

**Issue by GitHayato** [TechUni2020/TechUni-hp#7]
## 概要
READMEには
- eslint
- prettier
- jest

が仕様技術として書かれているが、mainブランチに`.eslintrc.js`や`.prettierc.js`、`jest.config.js`がなく、また、使用されているコードが見当たらない

## 改善
- eslint, prettierを用いてコードの整形を自動化する
- unit testを実装する？

**Comment by shouhi** [comment]
すいません。
テストに関しては書こうと思ったが結局せもういいやとなりました。

READMEは最初の方に書いてたものなので後に使うであろう使用技術含めて書いてたので修正します🙇‍♂️

**Comment by GitHayato** [comment]
eslint, prettierは貢献できそうなら貢献します〜

**Comment by shouhi** [comment]
> eslint, prettierは貢献できそうなら貢献します〜
ぜひお願いしたい！！
